import fs from 'node:fs';
import path from 'node:path';
import { SentinelConfig } from '../types.js';

export function generateArtilleryScript(config: SentinelConfig): string {
  const targetEndpoints = config.endpoints.slice(0, 5);

  const scenariosYaml = targetEndpoints
    .map((ep) => {
      const isPost = ep.method === 'POST';
      const bodySnippet = isPost && ep.sampleBody ? `\n            json:\n              ${JSON.stringify(ep.sampleBody)}` : '';
      return `      - ${ep.method.toLowerCase()}:
          url: "${ep.path}"${bodySnippet}`;
    })
    .join('\n');

  return `# ==============================================================================
# Auto-generated Artillery Synthetic Load & Resilience Test
# Generated by Sentinel-QA
# ==============================================================================
config:
  target: "{{ $processEnvironment.BASE_URL || '${config.baseUrl}' }}"
  phases:
    - duration: 10
      arrivalRate: 5
      name: "Warm-up phase"
    - duration: 20
      arrivalRate: 15
      rampTo: 50
      name: "Ramp-up phase"
    - duration: 20
      arrivalRate: 50
      name: "Sustained peak load"
  defaults:
    headers:
      User-Agent: "Artillery-Sentinel-QA/1.0"
      ${config.auth?.authHeader || 'Authorization'}: "${config.auth?.tokenPrefix || 'Bearer '}{{ $processEnvironment.USER_TOKEN || '${config.auth?.userToken || ''}' }}"
  ensure:
    p95: ${config.stress?.thresholds?.p95LatencyMs || 300}
    p99: ${config.stress?.thresholds?.p99LatencyMs || 600}
    maxErrorRate: ${config.stress?.thresholds?.maxErrorRatePercent || 2}

scenarios:
  - name: "API Flow Stress"
    flow:
${scenariosYaml}
`;
}

export function saveArtilleryScript(config: SentinelConfig, outputPath?: string): string {
  const content = generateArtilleryScript(config);
  const outDir = path.resolve(process.cwd(), config.outputDir || './sentinel-reports');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  const file = outputPath || path.join(outDir, 'artillery-stress-test.yml');
  fs.writeFileSync(file, content, 'utf-8');
  return file;
}
