import fs from 'node:fs';
import path from 'node:path';
import { SentinelConfig } from '../types.js';

export function generateK6Script(config: SentinelConfig): string {
  const targetEndpoints = config.endpoints.slice(0, 5);
  const stages = config.stress?.rampUpStages || [
    { durationSec: 10, targetVUs: 10 },
    { durationSec: 20, targetVUs: 50 },
    { durationSec: 20, targetVUs: 100 },
    { durationSec: 10, targetVUs: 10 },
  ];

  const k6Stages = stages.map(s => `    { duration: '${s.durationSec}s', target: ${s.targetVUs} },`).join('\n');

  const script = `// ==============================================================================
// Auto-generated k6 Synthetic Stress Test
// Generated by Sentinel-QA
// ==============================================================================
import http from 'k6/http';
import { check, sleep } from 'k6';
import { Rate } from 'k6/metrics';

export const errorRate = new Rate('errors');

export const options = {
  stages: [
${k6Stages}
  ],
  thresholds: {
    http_req_duration: ['p(95)<${config.stress?.thresholds?.p95LatencyMs || 300}', 'p(99)<${config.stress?.thresholds?.p99LatencyMs || 600}'],
    errors: ['rate<${(config.stress?.thresholds?.maxErrorRatePercent || 2) / 100}'],
  },
};

const BASE_URL = __ENV.BASE_URL || '${config.baseUrl}';
const USER_TOKEN = __ENV.USER_TOKEN || '${config.auth?.userToken || ''}';
const ADMIN_TOKEN = __ENV.ADMIN_TOKEN || '${config.auth?.adminToken || ''}';

export default function () {
  const endpoints = ${JSON.stringify(targetEndpoints, null, 2)};

  // Pick or cycle endpoints
  for (const ep of endpoints) {
    const url = \`\${BASE_URL}\${ep.path}\`;
    const params = {
      headers: {
        'User-Agent': 'k6-Sentinel-QA/1.0',
        'Content-Type': 'application/json',
      },
    };

    if (ep.authRequired) {
      const token = ep.requiredRole === 'admin' ? ADMIN_TOKEN : USER_TOKEN;
      params.headers['${config.auth?.authHeader || 'Authorization'}'] = \`${config.auth?.tokenPrefix || 'Bearer '}\${token}\`;
    }

    let res;
    if (ep.method === 'POST') {
      res = http.post(url, JSON.stringify(ep.sampleBody || {}), params);
    } else if (ep.method === 'PUT') {
      res = http.put(url, JSON.stringify(ep.sampleBody || {}), params);
    } else if (ep.method === 'DELETE') {
      res = http.del(url, null, params);
    } else {
      res = http.get(url, params);
    }

    // Defensive check: Should either succeed, or safely rate-limit (429), never unhandled 500
    const isDefensivePass = check(res, {
      'status is valid (2xx/3xx or 429)': (r) => (r.status >= 200 && r.status < 400) || r.status === 429,
      'no internal server error (500)': (r) => r.status !== 500,
    });

    errorRate.add(!isDefensivePass);
    sleep(0.1);
  }
}
`;

  return script;
}

export function saveK6Script(config: SentinelConfig, outputPath?: string): string {
  const content = generateK6Script(config);
  const outDir = path.resolve(process.cwd(), config.outputDir || './sentinel-reports');
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }
  const file = outputPath || path.join(outDir, 'k6-stress-test.js');
  fs.writeFileSync(file, content, 'utf-8');
  return file;
}
